#!/usr/bin/env python3
"""
build_library.py — SEO, analytics and chrome for frameworks.dianasimpsonhernandez.com

    python3 build_library.py          # inject head tags + analytics into every page, write sitemap/robots/404
    python3 build_library.py --og     # also render 1200×630 preview cards for pages that have none

Idempotent: everything injected sits between <!--dsh:head--> … <!--dsh:/head--> markers and is
replaced on each run, so legacy pages keep their own CSS/JS untouched. New pages (lever, recall,
stake, case study) are generated by their own modules in pages/ and then treated like any other.
Page metadata comes from data/frameworks.json (listed) and META below (unlisted).
"""
from __future__ import annotations
import json, os, re, sys, datetime, html as H

ROOT = os.path.dirname(os.path.abspath(__file__))
DOMAIN = "https://frameworks.dianasimpsonhernandez.com"
MAIN = "https://dianasimpsonhernandez.com"
# Umami Cloud (free). Same Website ID as the main site — one website covers both hosts. Empty = no script emitted.
UMAMI_WEBSITE_ID = "a98055b4-17b2-4091-b09e-3b3b5b34b4ad"
ANALYTICS = (f'<script defer src="https://cloud.umami.is/script.js" data-website-id="{UMAMI_WEBSITE_ID}"></script>'
             if UMAMI_WEBSITE_ID.strip() else "<!-- analytics: set UMAMI_WEBSITE_ID in build_library.py -->")
TODAY = datetime.date.today().isoformat()

# Unlisted pages (not in frameworks.json) still get correct SEO. noindex keeps client-specific pages out of search.
META = {
    "index": {"title": "Open Frameworks — the DSH library", "description": "Interactive frameworks, consulting methods and case studies for AI-native operators, by Diana Simpson-Hernandez. Versioned. Forkable. Free to run.", "type": "website"},
    "quantum-and-ai": {"title": "The Curious Universe — quantum & AI, explained for the curious", "description": "A guided course on quantum computing and AI for curious non-physicists. Aeon Academy, by Diana Simpson-Hernandez."},
    "frequency": {"title": "The Frequency Menu — sound and frequency reference", "description": "A reference menu of frequencies and sound-therapy protocols, with what each is claimed to do and the evidence grade."},
    "frequency-studio": {"title": "Frequency Studio — an interactive tone generator", "description": "Generate, layer and export frequencies in the browser. Companion to the Frequency Menu."},
    "flywheel": {"extra_css": "@media(max-width:700px){.grid>*{min-width:0}#dimensions{max-width:100%}}"},
    "rediscovery-canvas": {"extra_css": "@media(max-width:700px){.progress{margin-left:0;margin-right:0}.log-row{flex-wrap:wrap}.log-row input{max-width:100%;min-width:0}}"},
    "launcher": {"title": "Framework Launcher", "description": "Quick launcher for every DSH framework.", "noindex": True},
    "read-the-lead": {"title": "Read the Lead — a quick game for estate agents", "description": "Label the lead: a two-minute game on reading buyer intent, built on synthetic data.", "noindex": True},
    "STFC_faq": {"title": "Aletheai × STFC — technical FAQ", "description": "Technical FAQ for the Aletheai STFC application.", "noindex": True},
}

def load_frameworks():
    with open(os.path.join(ROOT, "data", "frameworks.json"), encoding="utf-8") as f:
        return json.load(f)["frameworks"]

def page_meta(slug: str, fw: dict | None):
    if fw:
        return {"title": f"{fw['title']} — {fw['subtitle']}", "description": fw["summary"], "type": "article",
                "noindex": False, "category": fw["category"], "name": fw["title"], "extra_css": META.get(slug, {}).get("extra_css", "")}
    m = dict(META.get(slug, {"title": slug, "description": ""}))
    m.setdefault("type", "article"); m.setdefault("noindex", False); m.setdefault("name", m["title"].split(" — ")[0])
    return m

def jsonld(slug, m, url):
    person = {"@type": "Person", "name": "Diana Simpson-Hernandez", "url": MAIN + "/", "sameAs": [MAIN + "/", "https://linkedin.com/in/dianasimpson", "https://www.youtube.com/@DianaSimpsonHernandez"]}
    if slug == "index":
        return {"@context": "https://schema.org", "@type": "CollectionPage", "name": "Open Frameworks", "url": url, "author": person,
                "isPartOf": {"@type": "WebSite", "name": "Diana Simpson-Hernandez", "url": MAIN + "/"}}
    kind = {"Course": "Course", "Case Study": "Article", "Method": "TechArticle"}.get(m.get("category", ""), "CreativeWork")
    d = {"@context": "https://schema.org", "@type": kind, "name": m["name"], "headline": m["title"], "description": m["description"], "url": url,
         "author": person, "publisher": person, "inLanguage": "en", "isAccessibleForFree": True, "dateModified": TODAY}
    if kind == "Course":
        d["provider"] = person; d["offers"] = {"@type": "Offer", "price": "0", "priceCurrency": "GBP", "availability": "https://schema.org/InStock", "url": url}
        d["hasCourseInstance"] = [{"@type": "CourseInstance", "courseMode": "online", "courseWorkload": "PT8H"}]
    return d

def head_block(slug, m, has_preview):
    path = "/" if slug == "index" else f"/{slug}/"
    url = DOMAIN + path
    og = f"{DOMAIN}/assets/preview-{'library' if slug=='index' else slug}.png" if has_preview else f"{DOMAIN}/assets/preview-library.png"
    robots = '<meta name="robots" content="noindex,follow">' if m.get("noindex") else '<meta name="robots" content="index,follow,max-image-preview:large">'
    t = H.escape(m["title"]); d = H.escape(m["description"])
    return f"""<!--dsh:head-->
<meta name="description" content="{d}">
<link rel="canonical" href="{url}">
{robots}
<meta name="author" content="Diana Simpson-Hernandez">
<meta property="og:type" content="{m.get('type','article')}"><meta property="og:site_name" content="Open Frameworks · Diana Simpson-Hernandez"><meta property="og:locale" content="en_GB">
<meta property="og:url" content="{url}"><meta property="og:title" content="{t}"><meta property="og:description" content="{d}">
<meta property="og:image" content="{og}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="{t}">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{t}"><meta name="twitter:description" content="{d}"><meta name="twitter:image" content="{og}">
<link rel="sitemap" type="application/xml" href="/sitemap.xml">
{ANALYTICS}
<script type="application/ld+json">{json.dumps(jsonld(slug, m, url), ensure_ascii=False)}</script>
{('<style>'+m['extra_css']+'</style>') if m.get('extra_css') else ''}
<!--dsh:/head-->"""

STRIP = [  # legacy tags the block replaces
    re.compile(r'<meta\s+name="description"[^>]*>\s*', re.I),
    re.compile(r'<meta\s+(?:property|name)="(?:og:|twitter:)[^"]*"[^>]*>\s*', re.I),
    re.compile(r'<link\s+rel="canonical"[^>]*>\s*', re.I),
    re.compile(r'<!--dsh:head-->.*?<!--dsh:/head-->\s*', re.S),
]

def inject(path, slug, m, has_preview):
    s = open(path, encoding="utf-8").read()
    for rx in STRIP: s = rx.sub("", s)
    if not re.search(r"<title>", s, re.I):
        s = re.sub(r"(<head[^>]*>)", r"\1\n<title>" + H.escape(m["title"]) + "</title>", s, count=1, flags=re.I)
    s = re.sub(r"(</head>)", head_block(slug, m, has_preview) + "\n\\1", s, count=1, flags=re.I)
    tmp = path + ".tmp"; open(tmp, "w", encoding="utf-8").write(s); os.replace(tmp, path)
    return len(s)

def all_pages():
    fws = {f["url"].strip("/"): f for f in load_frameworks()}
    out = [("index", os.path.join(ROOT, "index.html"), None)]
    for d in sorted(os.listdir(ROOT)):
        p = os.path.join(ROOT, d, "index.html")
        if os.path.isfile(p) and d not in ("assets", "data", "styles", "pages", "og"):
            out.append((d, p, fws.get(d)))
    return out

def build_404():
    body = f"""<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Not found — Open Frameworks</title><meta name="robots" content="noindex"><link rel="stylesheet" href="/assets/fonts/fonts.css"><link rel="stylesheet" href="/styles/main.css">
{ANALYTICS}
<style>.nf{{min-height:70vh;display:flex;flex-direction:column;justify-content:center;gap:1rem;max-width:60ch}}.nf h1{{font-size:clamp(2.4rem,7vw,5rem);line-height:1;letter-spacing:-.02em}}.nf a{{color:var(--accent);font-weight:600}}</style></head>
<body><div class="container nf"><span class="eyebrow">404</span><h1>That framework moved.</h1><p>The library was rebuilt in September 2026. Everything is still here — start from the index.</p>
<p><a href="/">Browse the library →</a> &nbsp; <a href="{MAIN}/">Main site →</a></p></div></body></html>"""
    open(os.path.join(ROOT, "404.html"), "w", encoding="utf-8").write(body)

def build_sitemap(pages):
    urls = ""
    for slug, path, fw in pages:
        m = page_meta(slug, fw)
        if m.get("noindex"): continue
        loc = DOMAIN + ("/" if slug == "index" else f"/{slug}/")
        urls += f"<url><loc>{loc}</loc><lastmod>{TODAY}</lastmod><changefreq>monthly</changefreq><priority>{'1.0' if slug=='index' else '0.8'}</priority></url>"
    open(os.path.join(ROOT, "sitemap.xml"), "w").write(f'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">{urls}</urlset>\n')
    open(os.path.join(ROOT, "robots.txt"), "w").write(f"User-agent: *\nAllow: /\nDisallow: /404.html\nDisallow: /launcher/\nDisallow: /STFC_faq/\n\nSitemap: {DOMAIN}/sitemap.xml\n")

OG = """<!DOCTYPE html><html><head><meta charset="utf-8"><style>
@font-face{font-family:'Schibsted Grotesk';font-weight:400 900;src:url('data:font/woff2;base64,__SG__') format('woff2')}
@font-face{font-family:'Martian Mono';font-weight:100 800;src:url('data:font/woff2;base64,__MM__') format('woff2')}
body{margin:0;width:1200px;height:630px;background:#fff;color:#1A1633;font-family:'Schibsted Grotesk',sans-serif;position:relative;overflow:hidden}
.bar{position:absolute;left:0;top:0;width:1200px;height:16px;background:linear-gradient(100deg,#5B4BC4 6%,#8A7BE8 46%,#F96167 94%)}
.k{position:absolute;left:72px;top:76px;font:500 18px 'Martian Mono';letter-spacing:.12em;text-transform:uppercase;color:#5B4BC4}
.t{position:absolute;left:72px;top:140px;width:1040px;font:800 __SIZE__px/1.0 'Schibsted Grotesk';letter-spacing:-.03em;color:#1A1633}
.s{position:absolute;left:72px;bottom:130px;width:1000px;font:400 28px/1.35 'Schibsted Grotesk';color:#3A3560}
.d{position:absolute;left:72px;bottom:56px;font:500 16px 'Martian Mono';letter-spacing:.1em;text-transform:uppercase;color:#6E6A8A}.d b{color:#B3252B}
.c{position:absolute;right:72px;top:70px;font:500 14px 'Martian Mono';letter-spacing:.1em;text-transform:uppercase;color:#fff;background:#1A1633;padding:10px 14px;border-radius:6px}
</style></head><body><div class="bar"></div><div class="k">Open Frameworks · Diana Simpson-Hernandez</div><div class="c">__CAT__</div><div class="t">__TITLE__</div><div class="s">__SUB__</div><div class="d">frameworks.dianasimpsonhernandez.com <b>·</b> free to run</div></body></html>"""

def build_og(pages, force=False):
    from playwright.sync_api import sync_playwright
    import base64
    fdir = os.path.join(ROOT, "assets", "fonts")
    b64 = lambda n: base64.b64encode(open(os.path.join(fdir, n), "rb").read()).decode()
    with sync_playwright() as pw:
        b = pw.chromium.launch(); pg = b.new_page(viewport={"width": 1200, "height": 630})
        for slug, path, fw in pages:
            out = os.path.join(ROOT, "assets", f"preview-{'library' if slug=='index' else slug}.png")
            if os.path.exists(out) and not force: continue
            m = page_meta(slug, fw)
            if m.get("noindex"): continue
            title = fw["title"] if fw else m["name"]; sub = fw["subtitle"] if fw else m["description"]
            cat = (fw["category"] if fw else "Library").upper()
            size = 104 if len(title) < 16 else 84 if len(title) < 26 else 64
            html = OG.replace("__SG__", b64("SchibstedGrotesk-var.woff2")).replace("__MM__", b64("MartianMono-var.woff2")).replace("__TITLE__", H.escape(title)).replace("__SUB__", H.escape(sub)).replace("__CAT__", H.escape(cat)).replace("__SIZE__", str(size))
            pg.set_content(html, wait_until="load"); pg.evaluate("document.fonts.ready"); pg.wait_for_timeout(200)
            pg.screenshot(path=out, type="png"); print(f"  ✓ {os.path.relpath(out, ROOT)}")
        b.close()

if __name__ == "__main__":
    pages = all_pages()
    if "--og" in sys.argv: build_og(pages, force="--force" in sys.argv)
    print("injecting head + analytics")
    for slug, path, fw in pages:
        m = page_meta(slug, fw)
        prev = os.path.exists(os.path.join(ROOT, "assets", f"preview-{'library' if slug=='index' else slug}.png"))
        n = inject(path, slug, m, prev); print(f"  ✓ {slug:28} {n//1024:3} KB  preview={'y' if prev else '-'}  {'noindex' if m.get('noindex') else ''}")
    build_404(); build_sitemap(pages); print("  ✓ 404.html, sitemap.xml, robots.txt\ndone")
